// Copyright 2023-Present Soma Notes

// Debounce
export const API_REQUEST_DEBOUNCE_TIME_MILLIS = 1000;
export const UI_UPDATE_DEBOUNCE_TIME_MILLIS = 200;

// UI
export const DEFAULT_LEFT_PANE_WIDTH = "30%";

export const TOAST_TIMEOUT_MILLIS = 3_500;
export const TOAST_MAX_COUNT = 3;

// Notes
export const MAX_FREE_NOTE_COUNT = 100;
export const MAX_FREE_NOTE_CONTENT_LENGTH = 100;

export const MAX_PREMIUM_NOTE_COUNT = 1_000;
export const MAX_PREMIUM_NOTE_CONTENT_LENGTH = 250;

export const MAX_PROFESSIONAL_NOTE_COUNT = 10_000;
export const MAX_PROFESSIONAL_NOTE_CONTENT_LENGTH = 1_000;

// Journals
export const MAX_FREE_JOURNAL_COUNT = 100;
export const MAX_FREE_JOURNAL_CONTENT_LENGTH = 1_000;

export const MAX_PREMIUM_JOURNAL_COUNT = 1_000;
export const MAX_PREMIUM_JOURNAL_CONTENT_LENGTH = 1_500;

export const MAX_PROFESSIONAL_JOURNAL_COUNT = 10_000;
export const MAX_PROFESSIONAL_JOURNAL_CONTENT_LENGTH = 2_000;

// Tasks
export const MAX_FREE_TASK_COUNT = 10;
export const MAX_FREE_TASK_CONTENT_LENGTH = 250;

export const MAX_PREMIUM_TASK_COUNT = 100;
export const MAX_PREMIUM_TASK_CONTENT_LENGTH = 500;

export const MAX_PROFESSIONAL_TASK_COUNT = 1_000;
export const MAX_PROFESSIONAL_TASK_CONTENT_LENGTH = 1_000;

// Admin overrides (strings)
export const ADMIN_GITHUB_USER_IDS = [];
