// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_journals_index from "./routes/api/journals/index.ts";
import * as $api_notes_index from "./routes/api/notes/index.ts";
import * as $api_signin_index from "./routes/api/signin/index.ts";
import * as $api_signout_index from "./routes/api/signout/index.ts";
import * as $api_tasks_index from "./routes/api/tasks/index.ts";
import * as $index from "./routes/index.tsx";
import * as $journals_index from "./routes/journals/index.tsx";
import * as $notes_noteId_index from "./routes/notes/[noteId]/index.tsx";
import * as $notes_index from "./routes/notes/index.tsx";
import * as $tasks_index from "./routes/tasks/index.tsx";
import * as $user_settings_index from "./routes/user/settings/index.tsx";
import * as $user_statistics_index from "./routes/user/statistics/index.tsx";
import * as $user_tasks_index from "./routes/user/tasks/index.tsx";
import * as $DoublePaneIsland from "./islands/DoublePaneIsland.tsx";
import * as $JournalViewerIsland from "./islands/JournalViewerIsland.tsx";
import * as $NoteViewerPageIsland from "./islands/NoteViewerPageIsland.tsx";
import * as $TasksViewerIsland from "./islands/TasksViewerIsland.tsx";
import * as $UserSettingsIsland from "./islands/UserSettingsIsland.tsx";
import * as $UserStatisticsIsland from "./islands/UserStatisticsIsland.tsx";
import * as $UserTasksIsland from "./islands/UserTasksIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/journals/index.ts": $api_journals_index,
    "./routes/api/notes/index.ts": $api_notes_index,
    "./routes/api/signin/index.ts": $api_signin_index,
    "./routes/api/signout/index.ts": $api_signout_index,
    "./routes/api/tasks/index.ts": $api_tasks_index,
    "./routes/index.tsx": $index,
    "./routes/journals/index.tsx": $journals_index,
    "./routes/notes/[noteId]/index.tsx": $notes_noteId_index,
    "./routes/notes/index.tsx": $notes_index,
    "./routes/tasks/index.tsx": $tasks_index,
    "./routes/user/settings/index.tsx": $user_settings_index,
    "./routes/user/statistics/index.tsx": $user_statistics_index,
    "./routes/user/tasks/index.tsx": $user_tasks_index,
  },
  islands: {
    "./islands/DoublePaneIsland.tsx": $DoublePaneIsland,
    "./islands/JournalViewerIsland.tsx": $JournalViewerIsland,
    "./islands/NoteViewerPageIsland.tsx": $NoteViewerPageIsland,
    "./islands/TasksViewerIsland.tsx": $TasksViewerIsland,
    "./islands/UserSettingsIsland.tsx": $UserSettingsIsland,
    "./islands/UserStatisticsIsland.tsx": $UserStatisticsIsland,
    "./islands/UserTasksIsland.tsx": $UserTasksIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
